### PR TITLE
Make Contracts Pausable

### PR DESCRIPTION
**Pull request by MayankMittal1**

### CODE REVIEW

**Review by leonprou — COMMENTED** [review]
Hi @MayankMittal1 , The changes look good
But I do wonder if we should add `whenNotPaused` to `_nonblockingLzReceive`. 
If we pause just one side of the bridge and `_nonblockingLzReceive` failed. There's a way to retry the call later when we unpause, right?

**Comment by MayankMittal1** [comment]
@leonprou but what if we want to pause only deposit / only withdraw, that would not be possible if we add ```whenNotPaused``` to ```_nonblockingLzReceive```

**Comment by leonprou** [comment]
@MayankMittal1 I see. Can you pease explain how _nonblockingLzReceive gets called?

**Comment by MayankMittal1** [comment]
@leonprou when you call bridge function, it get to the lz oracle which forwards the payload to the destination chain ```Endpoint``` contract, the Endpoint contract calls ```lzReceive``` function of the ```LzApp``` contract(every bridge is extended by this) which internally calls ```_nonblockingLzReceive```

**Comment by leonprou** [comment]
Alright I see,
I think we need to add `whenNotPaused` to `_nonblockingLzReceive` as well so in case there issue with LZ endpoints or bridge we can close it. What you mentioned about closing for one direction - for now it's not a concern - we can implement it later in a more granular way (maybe with limits).

**Comment by MayankMittal1** [comment]
@leonprou done

**Review by leonprou — APPROVED** [review]

**Comment by leonprou** [comment]
Thanks @MayankMittal1 
Approbed!

**Pull request merged**
